global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'contribution-metrics'
    static_configs:
      - targets: ['host.docker.internal:9464']  # Metrics endpoint from our app
    scrape_interval: 5s
    metrics_path: '/metrics'
